### ISSUE TITLE
SilverStripe 3.4?

### ISSUE THREAD

**Issue by spekulatius** [toastnz/twitter-card-meta#6]
Hello,

I saw that the version 3.4.x versions of framework and CMS are excluded in the composer.json file. Is this still up to date? Are there any plans for supporting 3.4.x?

Cheers,
Peter

**Comment by danaenz** [comment]
Yes, there are definitely plans to continue support into 3.4. Seeing as 4.0 is in alpha now, once I find some time I'll update the requirements and see how it handles 3.4.

**Comment by danaenz** [comment]
Twitter Card Meta works just fine with 3.4, so I've relaxed the CMS/Framework requirements to ~3.1. Fixed in [0.2.3](https://github.com/toastnz/twitter-card-meta/tree/0.2.3).
